version: '3'

networks: 
         backend:
                 services: 
                            nginx:
                                    image: ngnix:stable-alpine
                                    container_name: nginx
                                    ports: 
                                           -"8000:80"
                                    volumes: 
                                            - ./src:var/www
                                    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
                 dpends_on:
                                    -php
                                    -mysql

                 networks:
                                 - backend


                 mysql: 
                         image:  mysql:5.8.29
                         container_name: mysql
                         restart: unless-stopped
                         tty: true
                         ports: 
                                -"3306:3306"

                         enviroment:
                                    MYSQL_DATABASE: laravel
                                    MYSQL_USER: homestead
                                    MYSQL_PASSWORD: secret
                                    MYSQL_ROOT_PASSWORD: secret
                                    SERVICE_TAGS: dev
                                    SERVICE_NAME: mysql
                         networks: 
                                   - backend

                         php: 
                                build: 

                                       context:  .
                                       dockerfile: Dockerfile
                                container_name: php
                                volumes:   
                                          - ./src:/var/www/html
                                ports:
                                           - "9000:9000"

                                networks: 
                                         - backend         
